apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-cursos-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-cursos-server
  template:
    metadata:
      labels:
        app: ms-cursos-server
    spec:
      containers:
        - name: cursos
          image: 4xe1/cursos:latest
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              value: "8002"
            - name: DB_HOST
              value: "postgres14:5432"
            - name: DB_DATABASE
              value: db-ms-docker-kube
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: sasa
            - name: USUARIOS_URL
              value: "ms-usuarios-server:8001"