apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-usuarios-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-usuarios-server
  template:
    metadata:
      labels:
        app: ms-usuarios-server
    spec:
      containers:
      - image: 4xe1/usuarios:latest
        name: usuarios
        ports:
        - containerPort: 8001
